services:
  postgres:
    image: postgis/postgis:17-3.5
    container_name: postgres_ut_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: src
    container_name: taxi_web_app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DEBUG=true
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - FERNET_SECRET_KEY=${FERNET_SECRET_KEY:-dev-fernet-key-change-in-production}
      - TZ=Asia/Tehran
    volumes:
      - ./src:/app
    depends_on:
      - postgres
    command: bash -c "dos2unix ./start.sh && bash ./start.sh"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ut_db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  postgres_data:
